# Generated by Django 4.1.9 on 2023-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
