# Generated by Django 4.0.10 on 2023-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expert_query_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='domain',
            field=models.CharField(default='Overall', max_length=200),
            preserve_default=False,
        ),
    ]
