# Generated by Django 4.0.10 on 2023-09-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expert_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='photo',
            field=models.ImageField(default=None, upload_to='expert'),
            preserve_default=False,
        ),
    ]
